# docker network create simplilearn-phpinfo-network
# docker container run --detach --entrypoint /usr/bin/php --env OWNER=Sebastian --name simplilearn-phpinfo-src --network simplilearn-phpinfo-network --publish 82:8080 --restart always --user nobody --workdir /src/ simplilearn-phpinfo:labs -f index.php -S 0.0.0.0:8080

networks:
  simplilearn-phpinfo-network:
    internal: false
    
services:
  simplilearn-phpinfo:
    command:
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    entrypoint: /usr/bin/php
    environment:
      OWNER: Sebastian
    image: academiaonline/simplilearn-phpinfo:1.1-src
    networks:
      - simplilearn-phpinfo-network
    ports:
      - 82:8080
    user: nobody
    working_dir: /src/    

version: '3.8'    
